/* ============================================================
 * data.js — Telegram 开源项目数据集（共 89 条，已去重）
 * ------------------------------------------------------------
 * 字段说明：
 *   id          唯一标识
 *   name        owner/repo
 *   url         仓库地址
 *   lang        主要语言/技术栈
 *   cat         分类 key（见 CATEGORIES）
 *   desc        一句话功能
 *   tags        标签（用于搜索与扩展筛选）
 *   lic         许可证 SPDX（null = 无协议 / 待核实）
 *   licKind     permissive 宽松可商用 | copyleft 传染性 | unknown 未知
 *   comm        商用结论：yes 可商用 | caution 有条件 | no 不可 | unknown 待核实
 *   maint       active 活跃 | maintained 维护中 | stale 停更 | unknown 待核实
 *   seen        最近一次出现在搜索记录中的日期（真实数据）
 *   mentions    搜索历史中出现次数（真实统计）
 *   risk        normal | marketing 营销群发(违反ToS) | gambling
 *   conf        编辑字段可信度 high | medium | low
 *
 *   ── 以下字段由 bake-meta.mjs 从 GitHub API 实抓后烘焙，src:'api' 表示这些值已核实 ──
 *   pushedAt    最近一次提交日期（真实）
 *   stars       Star 数（真实）
 *   forks       Fork 数（真实）
 *   src         'api' = 该条目的许可/维护/时间/Star 来自 API 实测
 *
 * 数据可信度分布：
 *   ✅ 真实：seen / mentions（来自搜索记录）、src:'api' 条目的 lic / maint / pushedAt / stars / forks
 *   ⚠️ 推断：其余条目的 lic / maint / comm（未抓取到 API 数据，界面会标「待核实」）
 *
 * 补齐剩余仓库：node fetch-github-meta.mjs --missing && node bake-meta.mjs
 * ============================================================ */

const CATEGORIES = {
  framework: { label: '框架 / SDK / 库', color: '#4f8cff' },
  ai: { label: 'AI / LLM 机器人', color: '#a06bff' },
  manage: { label: '群组 / 频道管理', color: '#22c8a0' },
  forward: { label: '转发 / 自动化', color: '#f5a524' },
  shop: { label: '电商 / Mini App', color: '#ff6b9d' },
  tool: { label: '工具 / 文件 / 娱乐', color: '#38bdf8' },
  growth: { label: '营销群发（高风险）', color: '#ff5d5d' },
  awesome: { label: '资源 / 导航列表', color: '#8a94a6' },
};

const LANGS = ['Python', 'Go', 'Node.js', 'TypeScript', 'JavaScript', 'PHP', 'Markdown', 'n8n', '其他'];

const PROJECTS = [
  /* ---------- A. 框架 / SDK / 库 ---------- */
  { id:'aiogram', name:'aiogram/aiogram', url:'https://github.com/aiogram/aiogram', lang:'Python', cat:'framework',
    desc:'现代化、完全异步的 Telegram Bot API 框架（asyncio），支持 Router / FSM / 中间件。',
    tags:['Bot框架', '异步', 'asyncio'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'active',
    pushedAt:'2026-09-19', stars:5875, forks:966, src:'api',
    seen:'2026-09-19', mentions:3, risk:'normal', conf:'high' },
  { id:'ptb', name:'python-telegram-bot/python-telegram-bot', url:'https://github.com/python-telegram-bot/python-telegram-bot', lang:'Python', cat:'framework',
    desc:'老牌封装库，v20+ 全面 async，文档与 examples 最全，社区最大。',
    tags:['Bot框架', '封装库', 'examples'], lic:'GPL-3.0', licKind:'copyleft', comm:'caution', maint:'active',
    pushedAt:'2026-09-23', stars:29490, forks:6151, src:'api',
    seen:'2026-09-18', mentions:4, risk:'normal', conf:'high',
    note:'GPL-3.0：可商用，但分发修改版需开源；仅调用/链接使用不受影响' },
  { id:'telegraf', name:'telegraf/telegraf', url:'https://github.com/telegraf/telegraf', lang:'Node.js', cat:'framework',
    desc:'Node.js 生态最主流的 Bot 框架，中间件式设计，插件丰富。',
    tags:['Bot框架', '中间件'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'active',
    pushedAt:'2026-09-24', stars:9190, forks:939, src:'api',
    seen:'2026-09-17', mentions:3, risk:'normal', conf:'high',
    note:'MIT；2026-09-24 已恢复维护（此前自 2025-01 起休眠约 20 个月）——本次更新移除 Node 12 支持、CI 升到 Node 20-26，可重新纳入 Node.js 选型' },
  { id:'gotgbot', name:'PaulSonOfLars/gotgbot', url:'https://github.com/PaulSonOfLars/gotgbot', lang:'Go', cat:'framework',
    desc:'自动生成的 Telegram API Go 封装，API 风格刻意对齐 python-telegram-bot。',
    tags:['Bot框架', '代码生成'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'active',
    pushedAt:'2026-09-19', stars:723, forks:142, src:'api',
    seen:'2026-09-20', mentions:2, risk:'normal', conf:'high' },
  { id:'gtgbot', name:'go-telegram/bot', url:'https://github.com/go-telegram/bot', lang:'Go', cat:'framework',
    desc:'轻量的 Go Bot API 框架，不依赖第三方生成代码。',
    tags:['Bot框架', '轻量'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'active',
    pushedAt:'2026-09-11', stars:1844, forks:161, src:'api',
    seen:'2026-09-20', mentions:1, risk:'normal', conf:'high' },
  { id:'phpsdk', name:'irazasyed/telegram-bot-sdk', url:'https://github.com/irazasyed/telegram-bot-sdk', lang:'PHP', cat:'framework',
    desc:'PHP 版 Telegram Bot SDK，开箱支持 Laravel（ServiceProvider / Facade）。',
    tags:['Bot框架', 'Laravel'], lic:'BSD-3-Clause', licKind:'permissive', comm:'yes', maint:'active',
    pushedAt:'2026-08-20', stars:3301, forks:677, src:'api',
    seen:'2026-09-17', mentions:1, risk:'normal', conf:'low' },
  { id:'frappe', name:'leam-tech/frappe_telegram', url:'https://github.com/leam-tech/frappe_telegram', lang:'Python', cat:'framework',
    desc:'为 Frappe / ERPNext 提供 Telegram Bot 集成，把 ERP 操作与通知搬到 TG。',
    tags:['ERP', 'ERPNext', '企业集成'], lic:null, licKind:'unknown', comm:'unknown', maint:'stale',
    pushedAt:'2024-01-15', stars:44, forks:41, src:'api',
    seen:'2026-09-14', mentions:2, risk:'normal', conf:'low',
    note:'无 LICENSE 文件：法律上默认「保留所有权利」，商用前需先联系作者授权' },
  { id:'telegraftpl', name:'telegraf/template-bot', url:'https://github.com/telegraf/template-bot', lang:'Node.js', cat:'framework',
    desc:'Telegraf 官方脚手架模板，几分钟起一个 bot 项目。',
    tags:['模板', '脚手架'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'stale',
    pushedAt:'2019-11-28', stars:7, forks:6, src:'api',
    seen:'2026-09-20', mentions:1, risk:'normal', conf:'low' },
  { id:'vlytmpl', name:'vlymar1/aiogram-bot-template', url:'https://github.com/vlymar1/aiogram-bot-template', lang:'Python', cat:'framework',
    desc:'模块化 aiogram 模板：PostgreSQL + Redis + Docker Compose + Ruff + 用户指标管理面板。',
    tags:['模板', 'Docker', 'PostgreSQL', 'Redis'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'stale',
    pushedAt:'2025-06-20', stars:7, forks:1, src:'api',
    seen:'2026-09-20', mentions:2, risk:'normal', conf:'low' },
  { id:'uznetdev', name:'UznetDev/Aiogram-Bot-Template', url:'https://github.com/UznetDev/Aiogram-Bot-Template', lang:'Python', cat:'framework',
    desc:'aiogram 模板，自带管理面板：管用户、群发广告、增删管理员。',
    tags:['模板', '管理面板'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'stale',
    pushedAt:'2025-09-01', stars:43, forks:10, src:'api',
    seen:'2026-09-17', mentions:1, risk:'normal', conf:'low' },
  { id:'cfbuilder', name:'Hamed-Gharghi/Cloudflare-Telegram-bot-builder', url:'https://github.com/Hamed-Gharghi/Cloudflare-Telegram-bot-builder', lang:'TypeScript', cat:'framework',
    desc:'无代码搭建 Bot：Cloudflare Workers 自举 + D1/KV + 可视化规则编辑器，60 秒部署。',
    tags:['无代码', 'Cloudflare Workers', 'D1'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'active',
    pushedAt:'2026-08-03', stars:4, forks:2, src:'api',
    seen:'2026-09-13', mentions:1, risk:'normal', conf:'low' },
  { id:'amirabot', name:'developerAmira/telegram-bot', url:'https://github.com/developerAmira/telegram-bot', lang:'TypeScript', cat:'framework',
    desc:'波斯语/英语双语 Bot 管理面板，Cloudflare Workers + KV + Hono + Tailwind。',
    tags:['管理面板', 'Hono', 'KV'], lic:null, licKind:'unknown', comm:'unknown', maint:'active',
    pushedAt:'2026-09-11', stars:147, forks:257, src:'api',
    seen:'2026-09-20', mentions:2, risk:'normal', conf:'low',
    note:'无 LICENSE 文件：法律上默认「保留所有权利」，商用前需先联系作者授权' },

  /* ---------- B. AI / LLM 机器人 ---------- */
  { id:'dsbot', name:'yincongcyincong/telegram-deepseek-bot', url:'https://github.com/yincongcyincong/telegram-deepseek-bot', lang:'Go', cat:'ai',
    desc:'接 DeepSeek 等 LLM 的机器人，支持工具调用，让 Telegram 直接调你的各种工具。',
    tags:['DeepSeek', '工具调用', '中文文档'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'active',
    pushedAt:'2026-09-01', stars:1635, forks:240, src:'api',
    seen:'2026-09-20', mentions:3, risk:'normal', conf:'medium' },
  { id:'musebot', name:'yincongcyincong/MuseBot', url:'https://github.com/yincongcyincong/MuseBot', lang:'Go', cat:'ai',
    desc:'多平台 AI Bot：TG/Discord/Slack/飞书/钉钉/企微/QQ/微信，支持对话、生图、生视频。',
    tags:['多平台', '生图', '生视频', 'OpenRouter'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'active',
    pushedAt:'2026-09-01', stars:1635, forks:240, src:'api',
    seen:'2026-09-20', mentions:1, risk:'normal', conf:'medium' },
  { id:'langbot', name:'langbot-app/LangBot', url:'https://github.com/langbot-app/LangBot', lang:'Python', cat:'ai',
    desc:'生产级多平台机器人平台：Agent、知识库编排、插件系统，覆盖 11 个 IM 平台。',
    tags:['Agent', '知识库', '插件系统', 'Dify', 'n8n'], lic:'Apache-2.0', licKind:'permissive', comm:'yes', maint:'active',
    pushedAt:'2026-09-25', stars:17964, forks:1610, src:'api',
    seen:'2026-09-18', mentions:4, risk:'normal', conf:'medium',
    note:'Apache-2.0：可自由商用，无需开源修改；kjsssjj/LangBot 为镜像，不重复计' },
  { id:'abirds', name:'abirxdhack/DeepSeekBot', url:'https://github.com/abirxdhack/DeepSeekBot', lang:'Python', cat:'ai',
    desc:'Pyrogram + OpenRouter 的 DeepSeek R1 Bot，主打高并发多用户响应。',
    tags:['Pyrogram', 'OpenRouter', 'R1'], lic:null, licKind:'unknown', comm:'unknown', maint:'stale',
    pushedAt:'2025-04-30', stars:26, forks:0, src:'api',
    seen:'2026-09-20', mentions:1, risk:'normal', conf:'low',
    note:'无 LICENSE 文件：法律上默认「保留所有权利」，商用前需先联系作者授权' },
  { id:'cyrax', name:'genn-z-cyrax/cyrax_AI_oss', url:'https://github.com/genn-z-cyrax/cyrax_AI_oss', lang:'Python', cat:'ai',
    desc:'AI 多代理系统：动态模型编排，把意图路由到视觉/浏览器/桌面/代码 agent。',
    tags:['多代理', '编排', 'Agent'], lic:null, licKind:'unknown', comm:'unknown', maint:'maintained',
    pushedAt:'2026-04-04', stars:4, forks:0, src:'api',
    seen:'2026-09-20', mentions:2, risk:'normal', conf:'low',
    note:'无 LICENSE 文件：法律上默认「保留所有权利」，商用前需先联系作者授权' },
  { id:'novaagent', name:'Hsoofi82/NovaAgent', url:'https://github.com/Hsoofi82/NovaAgent', lang:'Python', cat:'ai',
    desc:'免费 Telegram AI Agent：生成并托管 Web App、生成游戏/图片/PDF/语音，10 分钟自托管。',
    tags:['AI Agent', '生成应用', '自托管'], lic:'AGPL-3.0', licKind:'copyleft', comm:'caution', maint:'active',
    pushedAt:'2026-09-21', stars:13, forks:3, src:'api',
    seen:'2026-09-20', mentions:2, risk:'normal', conf:'medium',
    note:'AGPL-3.0，商用需注意传染性条款' },
  { id:'wechatbot', name:'wangrongding/wechat-bot', url:'https://github.com/wangrongding/wechat-bot', lang:'Node.js', cat:'ai',
    desc:'多平台 IM AI 代理：TG/WhatsApp/Lark/微信，自动回复、社区分析、联系人管理、不活跃好友检测。',
    tags:['多平台', '自动回复', '社区分析'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'active',
    pushedAt:'2026-09-04', stars:11399, forks:1301, src:'api',
    seen:'2026-09-12', mentions:1, risk:'normal', conf:'medium' },
  { id:'ragsaas', name:'unusdon/ai-chatbot-saas', url:'https://github.com/unusdon/ai-chatbot-saas', lang:'TypeScript', cat:'ai',
    desc:'多租户 RAG 聊天机器人 SaaS：PDF/DOCX/URL 训练，输出 Web 挂件 + TG + WhatsApp，5 家 LLM。',
    tags:['RAG', '多租户', 'SaaS', 'pgvector'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'active',
    pushedAt:'2026-08-21', stars:1, forks:3, src:'api',
    seen:'2026-09-18', mentions:1, risk:'normal', conf:'medium' },
  { id:'restagent', name:'Walid-Amr/Restaurant-Ai-Agent', url:'https://github.com/Walid-Amr/Restaurant-Ai-Agent', lang:'n8n', cat:'ai',
    desc:'餐厅点餐 AI 助手：n8n + OpenRouter + Sheets + TG，自然语言下单、自动落表编号。',
    tags:['n8n', '点餐', '工作流'], lic:null, licKind:'unknown', comm:'unknown', maint:'active',
    pushedAt:'2026-09-11', stars:1, forks:0, src:'api',
    seen:'2026-09-20', mentions:1, risk:'normal', conf:'low',
    note:'无 LICENSE 文件：法律上默认「保留所有权利」，商用前需先联系作者授权' },
  { id:'expensebot', name:'varunmaheshwari30/telegram-expense-bot', url:'https://github.com/varunmaheshwari30/telegram-expense-bot', lang:'其他', cat:'ai',
    desc:'AI 记账机器人：Apps Script + Claude Haiku + Google Sheets，零服务器零托管费。',
    tags:['记账', 'Serverless', 'Claude'], lic:null, licKind:'unknown', comm:'unknown', maint:'maintained',
    pushedAt:'2026-05-01', stars:1, forks:0, src:'api',
    seen:'2026-09-20', mentions:2, risk:'normal', conf:'low',
    note:'无 LICENSE 文件：法律上默认「保留所有权利」，商用前需先联系作者授权' },
  { id:'parsehub', name:'z-mio/parse_hub_bot', url:'https://github.com/z-mio/parse_hub_bot', lang:'Python', cat:'ai',
    desc:'多平台聚合解析机器人，把各平台分享链接解析为可直接查看的内容。',
    tags:['解析', '聚合', '中文'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'active',
    pushedAt:'2026-09-19', stars:715, forks:64, src:'api',
    seen:'2026-09-20', mentions:1, risk:'normal', conf:'low' },
  { id:'lobsterai', name:'网易有道/LobsterAI', url:'https://github.com/netease-youdao/LobsterAI', lang:'TypeScript', cat:'ai',
    desc:'开源桌面级 AI 助手：数据分析、做 PPT、写文档、做视频、联网搜索；可远程下达指令。',
    tags:['桌面助手', '办公自动化', '大厂'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'active',
    pushedAt:'2026-09-25', stars:6070, forks:973, src:'api',
    seen:'2026-09-14', mentions:1, risk:'normal', conf:'medium' },
  { id:'mailassist', name:'AntonLukjanov/mail-telegram-assistant', url:'https://github.com/AntonLukjanov/mail-telegram-assistant', lang:'Python', cat:'ai',
    desc:'Mail.ru 企业邮箱 → Telegram 助理，带发件人白名单与 OpenRouter 处理。',
    tags:['邮箱', '白名单', '助理'], lic:null, licKind:'unknown', comm:'unknown', maint:'active',
    pushedAt:'2026-09-16', stars:0, forks:0, src:'api',
    seen:'2026-09-20', mentions:1, risk:'normal', conf:'low',
    note:'无 LICENSE 文件：法律上默认「保留所有权利」，商用前需先联系作者授权' },

  /* ---------- C. 群组 / 频道管理 ---------- */
  { id:'chanmgr', name:'leduchuong48-byte/telegram_chanel_manager_bot', url:'https://github.com/leduchuong48-byte/telegram_chanel_manager_bot', lang:'Python', cat:'manage',
    desc:'频道内容治理：实时去重 + 历史扫描 + 标签处理 + Web 面板，解决重复媒体堆积。',
    tags:['去重', '历史扫描', 'Web面板', '内容治理'], lic:null, licKind:'unknown', comm:'unknown', maint:'active',
    pushedAt:'2026-08-30', stars:0, forks:1, src:'api',
    seen:'2026-09-20', mentions:5, risk:'normal', conf:'medium',
    note:'无 LICENSE 文件：法律上默认「保留所有权利」，商用前需先联系作者授权' },
  { id:'autotg', name:'leduchuong48-byte/telegram_autotgtoward', url:'https://github.com/leduchuong48-byte/telegram_autotgtoward', lang:'Python', cat:'manage',
    desc:'WebUI 优先的自动转发 + RSS 平台：引导向导、规则过滤、AI 处理、日志监控，面向 NAS/HomeLab。',
    tags:['RSS', '转发', 'HomeLab', 'WebUI'], lic:'GPL-3.0', licKind:'copyleft', comm:'caution', maint:'maintained',
    pushedAt:'2026-04-15', stars:3, forks:1, src:'api',
    seen:'2026-09-20', mentions:3, risk:'normal', conf:'medium',
    note:'Docker 镜像 leduchuong/telegram_chanel_autotoward 为同一项目' },
  { id:'chanadmin', name:'ivanchik-byte/Telegram-Channel-Admin', url:'https://github.com/ivanchik-byte/Telegram-Channel-Admin', lang:'Python', cat:'manage',
    desc:'AI 频道内容管理：解析捐赠者频道 → 过滤广告 → LLM 改写帖子 → 发布队列 + 人工审核。',
    tags:['广告过滤', 'LLM改写', '发布队列', '审核'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'active',
    pushedAt:'2026-09-15', stars:2, forks:0, src:'api',
    seen:'2026-09-19', mentions:5, risk:'normal', conf:'medium',
    note:'搜索历史中出现次数最多的频道管理项目' },
  { id:'chanadminlite', name:'vlymar1/channel-admin-bot', url:'https://github.com/vlymar1/channel-admin-bot', lang:'Python', cat:'manage',
    desc:'轻量频道管理机器人，管理频道内容与用户。',
    tags:['轻量', '频道'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'stale',
    pushedAt:'2024-10-12', stars:4, forks:3, src:'api',
    seen:'2026-09-20', mentions:2, risk:'normal', conf:'low' },
  { id:'chtools', name:'alikm6/chToolsBot', url:'https://github.com/alikm6/chToolsBot', lang:'Python', cat:'manage',
    desc:'面向频道管理员的小工具集机器人。',
    tags:['工具集', '频道'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'stale',
    pushedAt:'2025-01-18', stars:54, forks:20, src:'api',
    seen:'2026-09-20', mentions:1, risk:'normal', conf:'low' },
  { id:'modzero', name:'mxvsh/modzero', url:'https://github.com/mxvsh/modzero', lang:'TypeScript', cat:'manage',
    desc:'Telegram 管理平台，设计感强的控制面板，可在 Vercel 快速部署。',
    tags:['控制面板', 'Vercel', '设计'], lic:null, licKind:'unknown', comm:'unknown', maint:'stale',
    pushedAt:'2024-02-10', stars:11, forks:7, src:'api',
    seen:'2026-09-20', mentions:1, risk:'normal', conf:'low',
    note:'无 LICENSE 文件：法律上默认「保留所有权利」，商用前需先联系作者授权' },
  { id:'wbb', name:'TheHamkerCat/WilliamButcherBot', url:'https://github.com/TheHamkerCat/WilliamButcherBot', lang:'Python', cat:'manage',
    desc:'经典群组管理机器人（Python / Pyrogram），反刷屏、admin 工具、黑名单等。',
    tags:['群管', 'Pyrogram', '经典'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'active',
    pushedAt:'2026-09-18', stars:420, forks:694, src:'api',
    seen:'2026-09-20', mentions:1, risk:'normal', conf:'low' },
  { id:'alita', name:'Divkix/Alita_Robot', url:'https://github.com/Divkix/Alita_Robot', lang:'Go', cat:'manage',
    desc:'Go + gotgbot 重写的群管机器人，比多数 Python 管理器更快更现代。',
    tags:['群管', 'Go', '高性能'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'active',
    pushedAt:'2026-09-26', stars:248, forks:322, src:'api',
    seen:'2026-09-19', mentions:1, risk:'normal', conf:'medium' },
  { id:'lucyna', name:'ryukaizen/lucyna', url:'https://github.com/ryukaizen/lucyna', lang:'TypeScript', cat:'manage',
    desc:'群管机器人，grammY + GramJS(MTProto)，兼具 Bot API 与用户态能力。',
    tags:['群管', 'grammY', 'MTProto'], lic:'AGPL-3.0', licKind:'copyleft', comm:'caution', maint:'stale',
    pushedAt:'2025-07-31', stars:25, forks:11, src:'api',
    seen:'2026-09-20', mentions:2, risk:'normal', conf:'low' },
  { id:'albedo', name:'Rachit-Pal/AlbedoBot', url:'https://github.com/Rachit-Pal/AlbedoBot', lang:'Python', cat:'manage',
    desc:'功能较全的综合型 Telegram 机器人。',
    tags:['综合型', '多功能'], lic:'BSD-2-Clause', licKind:'permissive', comm:'yes', maint:'stale',
    pushedAt:'2022-09-05', stars:11, forks:19, src:'api',
    seen:'2026-09-20', mentions:1, risk:'normal', conf:'low' },
  { id:'announce', name:'zero1max/Telegram-Announcement-Bot', url:'https://github.com/zero1max/Telegram-Announcement-Bot', lang:'Python', cat:'manage',
    desc:'公告流机器人：用户投稿 → 管理员批准/拒绝 → 通过的公告自动发到频道。',
    tags:['公告', '审核', '投稿'], lic:null, licKind:'unknown', comm:'unknown', maint:'stale',
    pushedAt:'2025-02-22', stars:0, forks:0, src:'api',
    seen:'2026-09-20', mentions:1, risk:'normal', conf:'low',
    note:'无 LICENSE 文件：法律上默认「保留所有权利」，商用前需先联系作者授权' },
  { id:'telepost', name:'redtidev1918/TelePost', url:'https://github.com/redtidev1918/TelePost', lang:'TypeScript', cat:'manage',
    desc:'频道投稿/审核/自动发布平台：Bot + Mini App + 多 Bot + HTTP API。',
    tags:['投稿', 'Mini App', 'HTTP API'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'active',
    pushedAt:'2026-09-24', stars:16, forks:3, src:'api',
    seen:'2026-09-20', mentions:1, risk:'normal', conf:'low' },
  { id:'mukesh', name:'noob-mukesh/MukeshRobot', url:'https://github.com/noob-mukesh/MukeshRobot', lang:'Python', cat:'manage',
    desc:'群管 + AI 二合一，ptb / telethon / pyrogram 混用，SQLAlchemy + MongoDB 存储。',
    tags:['群管', 'AI', 'MongoDB'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'stale',
    pushedAt:'2025-08-24', stars:113, forks:361, src:'api',
    seen:'2026-09-20', mentions:1, risk:'normal', conf:'low' },

  /* ---------- D. 转发 / 自动化 / Userbot ---------- */
  { id:'tgcf', name:'aahnik/tgcf', url:'https://github.com/aahnik/tgcf', lang:'Python', cat:'forward',
    desc:'终极自定义转发：实时同步、自动发帖、备份机器人、频道克隆、聊天转发、消息复制。',
    tags:['转发', '克隆', '备份', '实时同步'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'stale',
    pushedAt:'2024-05-06', stars:1622, forks:868, src:'api',
    seen:'2026-09-17', mentions:4, risk:'normal', conf:'medium',
    note:'kjsssjj/tgcf 为分叉，不重复计' },
  { id:'tgforwarder', name:'Heavrnl/TelegramForwarder', url:'https://github.com/Heavrnl/TelegramForwarder', lang:'Python', cat:'forward',
    desc:'多源转发 + 关键词过滤 + 正则替换 + RSS 订阅 + AI 处理 + 多平台推送。',
    tags:['转发', 'RSS', '正则', 'AI处理', '中文文档'], lic:'GPL-3.0', licKind:'copyleft', comm:'caution', maint:'maintained',
    pushedAt:'2026-02-10', stars:1277, forks:250, src:'api',
    seen:'2026-09-17', mentions:1, risk:'normal', conf:'medium',
    note:'中文文档，最贴合国内频道运营场景' },
  { id:'purplefwd', name:'PurpleSec/Forwarder', url:'https://github.com/PurpleSec/Forwarder', lang:'Python', cat:'forward',
    desc:'轻量的 Telegram 帖子转发机器人。',
    tags:['转发', '轻量'], lic:'GPL-3.0', licKind:'copyleft', comm:'caution', maint:'active',
    pushedAt:'2026-08-31', stars:0, forks:0, src:'api',
    seen:'2026-09-20', mentions:1, risk:'normal', conf:'low' },
  { id:'autofwd2', name:'devgaganin/Auto-Forward-Bot-V2', url:'https://github.com/devgaganin/Auto-Forward-Bot-V2', lang:'Python', cat:'forward',
    desc:'高级消息/文件转发，可保存频道群组里的受限（禁止转发）内容。',
    tags:['转发', '受限内容'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'maintained',
    pushedAt:'2026-01-24', stars:123, forks:268, src:'api',
    seen:'2026-09-13', mentions:1, risk:'normal', conf:'low',
    note:'保存"禁止转发"内容可能涉及版权与 ToS 风险' },
  { id:'tgwebhook', name:'Afdaan/telegram-webhook', url:'https://github.com/Afdaan/telegram-webhook', lang:'Python', cat:'forward',
    desc:'Telegram webhook 发送通道，把外部事件推送给 bot。',
    tags:['Webhook', '推送'], lic:null, licKind:'unknown', comm:'unknown', maint:'active',
    pushedAt:'2026-09-22', stars:0, forks:0, src:'api',
    seen:'2026-09-20', mentions:1, risk:'normal', conf:'low',
    note:'无 LICENSE 文件：法律上默认「保留所有权利」，商用前需先联系作者授权' },
  { id:'n8napprove', name:'enzoemir1/n8n-telegram-approval', url:'https://github.com/enzoemir1/n8n-telegram-approval', lang:'n8n', cat:'forward',
    desc:'给 n8n 工作流加"人在环"审批：Telegram 按钮审批 AI 内容流水线，工作流可导入。',
    tags:['n8n', '审批', 'Human-in-the-loop'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'active',
    pushedAt:'2026-08-20', stars:0, forks:0, src:'api',
    seen:'2026-09-20', mentions:1, risk:'normal', conf:'low' },
  { id:'hellbot', name:'The-HellBot/HellBot', url:'https://github.com/The-HellBot/HellBot', lang:'Python', cat:'forward',
    desc:'高性能 Telegram userbot（用户态自建机器人）。',
    tags:['Userbot', '插件'], lic:'GPL-3.0', licKind:'copyleft', comm:'caution', maint:'stale',
    pushedAt:'2024-06-03', stars:599, forks:2043, src:'api',
    seen:'2026-09-20', mentions:1, risk:'normal', conf:'low' },
  { id:'pagermaidpyro', name:'TeamPGM/PagerMaid-Pyro', url:'https://github.com/TeamPGM/PagerMaid-Pyro', lang:'Python', cat:'forward',
    desc:'高级多功能 userbot，插件体系成熟（Pyrogram 版）。',
    tags:['Userbot', 'Pyrogram', '插件'], lic:'AGPL-3.0', licKind:'copyleft', comm:'caution', maint:'active',
    pushedAt:'2026-07-12', stars:811, forks:99, src:'api',
    seen:'2026-09-18', mentions:1, risk:'normal', conf:'low' },
  { id:'pagermaidmod', name:'TeamPGM/PagerMaid-Modify', url:'https://github.com/TeamPGM/PagerMaid-Modify', lang:'Python', cat:'forward',
    desc:'高级多功能 userbot（Telethon 版）。',
    tags:['Userbot', 'Telethon'], lic:'GPL-3.0', licKind:'copyleft', comm:'caution', maint:'active',
    pushedAt:'2026-07-12', stars:41, forks:13, src:'api',
    seen:'2026-09-18', mentions:1, risk:'normal', conf:'low' },

  /* ---------- E. 电商 / 商店 / Mini App ---------- */
  { id:'shopbot', name:'ilyarolf/AiogramShopBot', url:'https://github.com/ilyarolf/AiogramShopBot', lang:'Python', cat:'shop',
    desc:'Aiogram3 开源电商机器人：卖虚拟+实物商品，加密货币支付，带推荐系统，最完整的开箱发卡店。',
    tags:['电商', '加密货币', '推荐系统', 'Docker'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'active',
    pushedAt:'2026-08-31', stars:238, forks:98, src:'api',
    seen:'2026-09-18', mentions:4, risk:'normal', conf:'medium' },
  { id:'goshop', name:'JumpCodeFrog/telegram-shop-bot', url:'https://github.com/JumpCodeFrog/telegram-shop-bot', lang:'Go', cat:'shop',
    desc:'Go 商店机器人：商品目录、Stars & USDT 支付、订阅制、Mini App、管理面板。',
    tags:['电商', 'Stars', 'USDT', '订阅'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'active',
    pushedAt:'2026-09-25', stars:17, forks:8, src:'api',
    seen:'2026-09-18', mentions:1, risk:'normal', conf:'low' },
  { id:'djangoshop', name:'itzddos/ecommerce-telegram-bot', url:'https://github.com/itzddos/ecommerce-telegram-bot', lang:'Python', cat:'shop',
    desc:'Django + Aiogram：Django Admin 管分类/子分类/商品，机器人含管理员端+客户端，带认证。',
    tags:['电商', 'Django', '后台管理'], lic:null, licKind:'unknown', comm:'unknown', maint:'stale',
    pushedAt:'2025-02-05', stars:33, forks:6, src:'api',
    seen:'2026-09-17', mentions:2, risk:'normal', conf:'low',
    note:'无 LICENSE 文件：法律上默认「保留所有权利」，商用前需先联系作者授权' },
  { id:'raulshop', name:'raulpy271/telegram_ecommerce', url:'https://github.com/raulpy271/telegram_ecommerce', lang:'Python', cat:'shop',
    desc:'商品销售机器人，销售员可自行增删改商品。',
    tags:['电商', '多销售员'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'stale',
    pushedAt:'2025-02-16', stars:127, forks:48, src:'api',
    seen:'2026-09-17', mentions:1, risk:'normal', conf:'low' },
  { id:'tgshop', name:'interlumpen/Telegram-shop', url:'https://github.com/interlumpen/Telegram-shop', lang:'Python', cat:'shop',
    desc:'商店模板：用户可充值余额并购买商品。',
    tags:['电商', '模板', '充值'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'active',
    pushedAt:'2026-07-27', stars:142, forks:72, src:'api',
    seen:'2026-09-18', mentions:2, risk:'normal', conf:'low' },
  { id:'tgshopphys', name:'interlumpen/Telegram-shop-Physical', url:'https://github.com/interlumpen/Telegram-shop-Physical', lang:'Python', cat:'shop',
    desc:'实物商品版商店模板：下单 + 配送流程。',
    tags:['电商', '实物', '配送'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'active',
    pushedAt:'2026-07-12', stars:16, forks:16, src:'api',
    seen:'2026-09-18', mentions:2, risk:'normal', conf:'low' },
  { id:'donskoyshop', name:'DaniilDonskoy/Shop-bot', url:'https://github.com/DaniilDonskoy/Shop-bot', lang:'Python', cat:'shop',
    desc:'🛒 商店机器人模板，适合快速二次开发。',
    tags:['电商', '模板'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'stale',
    pushedAt:'2025-08-24', stars:510, forks:152, src:'api',
    seen:'2026-09-18', mentions:3, risk:'normal', conf:'low' },
  { id:'w1pngshop', name:'w1png/shop-telegram-bot', url:'https://github.com/w1png/shop-telegram-bot', lang:'Python', cat:'shop',
    desc:'用于创建店铺的 Telegram 机器人（俄语文档）。',
    tags:['电商', '建店'], lic:'GPL-3.0', licKind:'copyleft', comm:'caution', maint:'stale',
    pushedAt:'2024-04-13', stars:182, forks:52, src:'api',
    seen:'2026-09-17', mentions:1, risk:'normal', conf:'low' },
  { id:'novastore', name:'unusdon/nova-store-telegram-mini-app', url:'https://github.com/unusdon/nova-store-telegram-mini-app', lang:'JavaScript', cat:'shop',
    desc:'Mini App 电商 UI 套件（原生 H5）：43 店铺页 + 34 后台页，无构建步骤，配置优先。',
    tags:['Mini App', '电商', '多语言', 'RTL', '免构建', 'Telegram Stars', 'TON'], lic:null, licKind:'unknown', comm:'unknown', maint:'active',
    pushedAt:'2026-07-29', stars:1, forks:2, src:'api',
    seen:'2026-09-18', mentions:4, risk:'normal', conf:'medium',
    note:'无 LICENSE 文件：法律上默认「保留所有权利」，商用前需先联系作者授权；4 种支付：Stars / TON / Stripe / 货到付款；云梦家纺等演示站即其部署实例' },
  { id:'novastorenext', name:'unusdon/nova-store-telegram-mini-app-nextjs', url:'https://github.com/unusdon/nova-store-telegram-mini-app-nextjs', lang:'TypeScript', cat:'shop',
    desc:'上一套的 Next.js 姊妹版：Next.js 15 + React 19，77 条路由，深浅色 + 多语言多支付。',
    tags:['Mini App', '电商', 'Next.js', '多语言', 'RTL'], lic:null, licKind:'unknown', comm:'unknown', maint:'active',
    pushedAt:'2026-07-29', stars:2, forks:1, src:'api',
    seen:'2026-09-18', mentions:4, risk:'normal', conf:'medium',
    note:'无 LICENSE 文件：法律上默认「保留所有权利」，商用前需先联系作者授权' },
  { id:'miniwoo', name:'mini-woo/mini-woo', url:'https://github.com/mini-woo/mini-woo', lang:'TypeScript', cat:'shop',
    desc:'把 WooCommerce 接进 Telegram Mini App，适合已有 WooCommerce 店铺的场景。',
    tags:['Mini App', 'WooCommerce', '电商'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'stale',
    pushedAt:'2024-08-15', stars:286, forks:82, src:'api',
    seen:'2026-09-18', mentions:2, risk:'normal', conf:'low' },
  { id:'tgcart', name:'kiran-venugopal/tgcart-mini-app', url:'https://github.com/kiran-venugopal/tgcart-mini-app', lang:'JavaScript', cat:'shop',
    desc:'电商类 Telegram 小程序，官方 Mini App 大赛三等奖作品。',
    tags:['Mini App', '电商', '获奖'], lic:null, licKind:'unknown', comm:'unknown', maint:'stale',
    pushedAt:'2024-11-12', stars:13, forks:11, src:'api',
    seen:'2026-09-18', mentions:1, risk:'normal', conf:'low',
    note:'无 LICENSE 文件：法律上默认「保留所有权利」，商用前需先联系作者授权' },
  { id:'farmtg', name:'bennyforweb4/farmtg-bot', url:'https://github.com/bennyforweb4/farmtg-bot', lang:'Python', cat:'shop',
    desc:'FarmTG Telegram 小程序自动化机器人。',
    tags:['Mini App', '自动化', '脚本'], lic:null, licKind:'unknown', comm:'unknown', maint:'maintained',
    pushedAt:'2026-06-20', stars:1, forks:0, src:'api',
    seen:'2026-09-18', mentions:1, risk:'normal', conf:'low',
    note:'无 LICENSE 文件：法律上默认「保留所有权利」，商用前需先联系作者授权' },
  { id:'botstore', name:'NishulDhakar/Telegram-Bots-Store', url:'https://github.com/NishulDhakar/Telegram-Bots-Store', lang:'Python', cat:'shop',
    desc:'"Bot 商店"：在一个地方发现、对比、使用多个 AI 机器人。',
    tags:['聚合', 'AI机器人'], lic:null, licKind:'unknown', comm:'unknown', maint:'maintained',
    pushedAt:'2026-06-08', stars:0, forks:0, src:'api',
    seen:'2026-09-13', mentions:1, risk:'normal', conf:'low',
    note:'无 LICENSE 文件：法律上默认「保留所有权利」，商用前需先联系作者授权' },

  /* ---------- F. 工具 / 文件 / 娱乐 ---------- */
  { id:'tgstate', name:'csznet/tgState', url:'https://github.com/csznet/tgState', lang:'Go', cat:'tool',
    desc:'把 Telegram 当对象存储：文件外链系统，不限文件大小与格式。',
    tags:['图床', '文件外链', '对象存储'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'stale',
    pushedAt:'2025-04-13', stars:1043, forks:182, src:'api',
    seen:'2026-09-13', mentions:1, risk:'normal', conf:'low' },
  { id:'fileshare', name:'CodeXBotz/File-Sharing-Bot', url:'https://github.com/CodeXBotz/File-Sharing-Bot', lang:'Python', cat:'tool',
    desc:'文件分享机器人：存帖子与文档，通过专属链接访问。',
    tags:['文件分享', '专属链接'], lic:'GPL-3.0', licKind:'copyleft', comm:'caution', maint:'maintained',
    pushedAt:'2025-12-28', stars:2413, forks:6408, src:'api',
    seen:'2026-09-20', mentions:1, risk:'normal', conf:'low' },
  { id:'paperless', name:'GeiserX/paperless-telegram-bot', url:'https://github.com/GeiserX/paperless-telegram-bot', lang:'Python', cat:'tool',
    desc:'全程用 Telegram 管理 Paperless-NGX：上传、搜索、打标签、整理文档。',
    tags:['文档管理', 'Paperless', '标签'], lic:'GPL-3.0', licKind:'copyleft', comm:'caution', maint:'active',
    pushedAt:'2026-09-01', stars:12, forks:2, src:'api',
    seen:'2026-09-13', mentions:1, risk:'normal', conf:'low' },
  { id:'scraper', name:'nuhmanpk/WebScrapper', url:'https://github.com/nuhmanpk/WebScrapper', lang:'Python', cat:'tool',
    desc:'网页抓取 / 爬虫机器人，主打快速易用。',
    tags:['爬虫', '抓取'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'maintained',
    pushedAt:'2026-03-19', stars:211, forks:116, src:'api',
    seen:'2026-09-20', mentions:1, risk:'normal', conf:'low' },
  { id:'dicebot', name:'deanxv/telegram-dice-bot', url:'https://github.com/deanxv/telegram-dice-bot', lang:'Python', cat:'tool',
    desc:'骰子娱乐机器人，群里掷骰子互动。',
    tags:['娱乐', '骰子', '中文'], lic:null, licKind:'unknown', comm:'unknown', maint:'active',
    pushedAt:'2026-07-17', stars:90, forks:34, src:'api',
    seen:'2026-09-13', mentions:1, risk:'normal', conf:'low',
    note:'无 LICENSE 文件：法律上默认「保留所有权利」，商用前需先联系作者授权' },
  { id:'durak', name:'Milesden/durak_bot', url:'https://github.com/Milesden/durak_bot', lang:'Python', cat:'tool',
    desc:'俄罗斯纸牌 Durak 对战机器人，aiogram 异步 + 模块化架构。',
    tags:['游戏', '卡牌', 'aiogram'], lic:null, licKind:'unknown', comm:'unknown', maint:'active',
    pushedAt:'2026-09-09', stars:1, forks:0, src:'api',
    seen:'2026-09-20', mentions:2, risk:'normal', conf:'low',
    note:'无 LICENSE 文件：法律上默认「保留所有权利」，商用前需先联系作者授权' },
  { id:'tempemail', name:'DuanNaiSheQu/cloudflare_temp_email', url:'https://github.com/DuanNaiSheQu/cloudflare_temp_email', lang:'TypeScript', cat:'tool',
    desc:'Cloudflare 免费临时域名邮箱：免费收发、支持附件、IMAP/SMTP，带 TG 通知。',
    tags:['临时邮箱', 'Cloudflare', 'IMAP/SMTP'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'maintained',
    pushedAt:'2026-05-21', stars:0, forks:0, src:'api',
    seen:'2026-09-13', mentions:1, risk:'normal', conf:'medium' },
  { id:'hamster', name:'vlymar1/Hamster-code-generator', url:'https://github.com/vlymar1/Hamster-code-generator', lang:'Python', cat:'tool',
    desc:'Hamster Kombat 促销码生成/分发机器人，含管理面板与用户通知系统。',
    tags:['促销码', '薅羊毛', '管理面板'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'active',
    pushedAt:'2026-09-21', stars:11, forks:6, src:'api',
    seen:'2026-09-20', mentions:1, risk:'normal', conf:'low' },

  /* ---------- G. 营销 / 群发（高风险） ---------- */
  { id:'massdm', name:'erfan4lx/Telegram-Mass-DM-Sender', url:'https://github.com/erfan4lx/Telegram-Mass-DM-Sender', lang:'Python', cat:'growth',
    desc:'向目标群组成员批量发送私信（Mass DM）。',
    tags:['群发', '私信', '高风险'], lic:'MIT', licKind:'permissive', comm:'no', maint:'maintained',
    pushedAt:'2025-10-14', stars:9, forks:1, src:'api',
    seen:'2026-09-20', mentions:2, risk:'marketing', conf:'low' },
  { id:'bulkpro', name:'erfan4lx/Telegram-Bulk-Message-Sender', url:'https://github.com/erfan4lx/Telegram-Bulk-Message-Sender', lang:'Python', cat:'growth',
    desc:'上一项的 Pro 版：多账号批量发信。',
    tags:['群发', '多账号', '高风险'], lic:null, licKind:'unknown', comm:'no', maint:'maintained',
    pushedAt:'2025-10-14', stars:11, forks:1, src:'api',
    seen:'2026-09-20', mentions:1, risk:'marketing', conf:'low',
    note:'无 LICENSE 文件：法律上默认「保留所有权利」，商用前需先联系作者授权' },
  { id:'amrbulk', name:'AmrNabil12/Telegram-Bulk-Sender', url:'https://github.com/AmrNabil12/Telegram-Bulk-Sender', lang:'Python', cat:'growth',
    desc:'基于 Telegram Web 自动化的群发：投递校验、媒体支持、重试、拟人化交互。',
    tags:['群发', 'Web自动化', '高风险'], lic:null, licKind:'unknown', comm:'no', maint:'active',
    pushedAt:'2026-09-02', stars:0, forks:0, src:'api',
    seen:'2026-09-20', mentions:1, risk:'marketing', conf:'low',
    note:'无 LICENSE 文件：法律上默认「保留所有权利」，商用前需先联系作者授权' },
  { id:'masssender', name:'BagroDeRose/TelegramMassSender', url:'https://github.com/BagroDeRose/TelegramMassSender', lang:'Python', cat:'growth',
    desc:'Windows 桌面群发管理工具，PySide6 + qasync + Telethon。',
    tags:['群发', '桌面应用', 'Telethon'], lic:'MIT', licKind:'permissive', comm:'no', maint:'active',
    pushedAt:'2026-09-16', stars:2, forks:0, src:'api',
    seen:'2026-09-20', mentions:1, risk:'marketing', conf:'low' },
  { id:'telesender', name:'Ziadtareks/TeleSender-Telegram-Groups-Auto-Sender', url:'https://github.com/Ziadtareks/TeleSender-Telegram-Groups-Auto-Sender', lang:'Python', cat:'growth',
    desc:'群组自动群发：自动删除、循环重发、FloodWait 处理。',
    tags:['群发', 'FloodWait', '高风险'], lic:'MIT', licKind:'permissive', comm:'no', maint:'active',
    pushedAt:'2026-09-18', stars:2, forks:0, src:'api',
    seen:'2026-09-20', mentions:1, risk:'marketing', conf:'low' },
  { id:'nexussender', name:'nexusquanthq-art/telegram-sender', url:'https://github.com/nexusquanthq-art/telegram-sender', lang:'Python', cat:'growth',
    desc:'GUI 发送工具：消息 / 图片 / 视频 / 文档。',
    tags:['群发', 'GUI'], lic:null, licKind:'unknown', comm:'no', maint:'active',
    pushedAt:'2026-09-13', stars:0, forks:0, src:'api',
    seen:'2026-09-20', mentions:1, risk:'marketing', conf:'low',
    note:'无 LICENSE 文件：法律上默认「保留所有权利」，商用前需先联系作者授权' },
  { id:'mktsoft', name:'sajjad-021/Telegram-Marketing-Software', url:'https://github.com/sajjad-021/Telegram-Marketing-Software', lang:'Python', cat:'growth',
    desc:'营销全家桶：群成员提取、自动回复、数据导出、广告投放。',
    tags:['营销', '采集', '导出', '高风险'], lic:'GPL-3.0', licKind:'copyleft', comm:'no', maint:'stale',
    pushedAt:'2024-06-06', stars:140, forks:16, src:'api',
    seen:'2026-09-20', mentions:1, risk:'marketing', conf:'low' },
  { id:'freesender', name:'free-985211/telegram-sender', url:'https://github.com/free-985211/telegram-sender', lang:'Python', cat:'growth',
    desc:'中文群发工具集：群发、群组采集、自动加群、云控助手。',
    tags:['群发', '采集', '加群', '中文', '高风险'], lic:null, licKind:'unknown', comm:'no', maint:'stale',
    pushedAt:'2024-12-16', stars:10, forks:0, src:'api',
    seen:'2026-09-20', mentions:1, risk:'marketing', conf:'low',
    note:'无 LICENSE 文件：法律上默认「保留所有权利」，商用前需先联系作者授权' },
  { id:'memberadder', name:'Telegram-Tools-Free/Telegram-Member-Adder-Free', url:'https://github.com/Telegram-Tools-Free/Telegram-Member-Adder-Free', lang:'Python', cat:'growth',
    desc:'免费拉人（Member Adder）工具，"Made in 2026"。',
    tags:['拉人', '加群', '高风险'], lic:null, licKind:'unknown', comm:'no', maint:'active',
    pushedAt:'2026-07-18', stars:7, forks:0, src:'api',
    seen:'2026-09-20', mentions:2, risk:'marketing', conf:'low',
    note:'无 LICENSE 文件：法律上默认「保留所有权利」，商用前需先联系作者授权' },
  { id:'hermanosender', name:'HermanoPiedra/TelegramSender', url:'https://github.com/HermanoPiedra/TelegramSender', lang:'Python', cat:'growth',
    desc:'Replit 上的 Telegram 发送脚本仓库。',
    tags:['发送', '脚本'], lic:null, licKind:'unknown', comm:'no', maint:'active',
    pushedAt:'2026-09-25', stars:0, forks:0, src:'api',
    seen:'2026-09-20', mentions:1, risk:'marketing', conf:'low',
    note:'无 LICENSE 文件：法律上默认「保留所有权利」，商用前需先联系作者授权' },
  { id:'autoreg', name:'lavalarkcorridor/Free-Telegram-Autoreg-Toolkit', url:'https://github.com/lavalarkcorridor/Free-Telegram-Autoreg-Toolkit', lang:'Python', cat:'growth',
    desc:'免费 Telegram 自动注册工具箱（批量注册账号）。',
    tags:['自动注册', '批量', '最高风险'], lic:null, licKind:'unknown', comm:'no', maint:'unknown',
    seen:'2026-09-13', mentions:1, risk:'marketing', conf:'low',
    note:'⚠️ 仓库已不存在（GitHub API 返回 404，作者账号也已注销），无法核实许可证；批量注册账号风险最高，强烈不建议使用' },
  { id:'duannai', name:'DuanNaiSheQu/Telegram-bot', url:'https://github.com/DuanNaiSheQu/Telegram-bot', lang:'其他', cat:'growth',
    desc:'号称"Telegram 机器人源码平台/开源社区"，实为资源分发聚合。',
    tags:['资源站', '聚合'], lic:'Unlicense', licKind:'permissive', comm:'yes', maint:'stale',
    pushedAt:'2025-07-01', stars:5, forks:1, src:'api',
    seen:'2026-09-17', mentions:2, risk:'marketing', conf:'low' },
  { id:'hashbac', name:'DuanNaiSheQu/-telegram', url:'https://github.com/DuanNaiSheQu/-telegram', lang:'JavaScript', cat:'growth',
    desc:'telegram 哈希百家乐（赌博类源码）。',
    tags:['赌博', '百家乐', '违规'], lic:'Apache-2.0', licKind:'permissive', comm:'no', maint:'maintained',
    pushedAt:'2025-11-01', stars:0, forks:0, src:'api',
    seen:'2026-09-13', mentions:2, risk:'gambling', conf:'low' },

  /* ---------- H. 资源 / 导航列表 ---------- */
  { id:'awesomebots', name:'erkcet/awesome-telegram-bots', url:'https://github.com/erkcet/awesome-telegram-bots', lang:'Markdown', cat:'awesome',
    desc:'Bot 资源精选：库、框架、工具、Mini App、社区 bot，持续维护。',
    tags:['Awesome', '导航', '持续维护'], lic:'CC0-1.0', licKind:'permissive', comm:'yes', maint:'active',
    pushedAt:'2026-09-18', stars:42, forks:46, src:'api',
    seen:'2026-09-17', mentions:3, risk:'normal', conf:'medium' },
  { id:'awesomesdk', name:'telegram-bot-sdk/awesome-telegram-bots', url:'https://github.com/telegram-bot-sdk/awesome-telegram-bots', lang:'Markdown', cat:'awesome',
    desc:'用 Telegram Bot SDK (PHP) 构建的 Bot 精选。',
    tags:['Awesome', 'PHP'], lic:'CC0-1.0', licKind:'permissive', comm:'yes', maint:'stale',
    pushedAt:'2023-11-06', stars:125, forks:16, src:'api',
    seen:'2026-09-20', mentions:1, risk:'normal', conf:'low' },
  { id:'awesometg', name:'ebertti/awesome-telegram', url:'https://github.com/ebertti/awesome-telegram', lang:'Markdown', cat:'awesome',
    desc:'群组、频道、机器人、库的综合合集。',
    tags:['Awesome', '合集'], lic:null, licKind:'unknown', comm:'unknown', maint:'active',
    pushedAt:'2026-09-21', stars:5883, forks:576, src:'api',
    seen:'2026-09-13', mentions:1, risk:'normal', conf:'low',
    note:'无 LICENSE 文件：法律上默认「保留所有权利」，商用前需先联系作者授权' },
  { id:'awesometma', name:'telegram-mini-apps-dev/awesome-telegram-mini-apps', url:'https://github.com/telegram-mini-apps-dev/awesome-telegram-mini-apps', lang:'Markdown', cat:'awesome',
    desc:'Telegram Mini Apps (TMA) 相关精选，做小程序必看。',
    tags:['Awesome', 'Mini App', '必看'], lic:'CC0-1.0', licKind:'permissive', comm:'yes', maint:'maintained',
    pushedAt:'2026-05-05', stars:1401, forks:145, src:'api',
    seen:'2026-09-18', mentions:1, risk:'normal', conf:'medium' },
  { id:'awesomecn', name:'DOS-AI-Tech/Awesome-Telegram-Chinese-2026', url:'https://github.com/DOS-AI-Tech/Awesome-Telegram-Chinese-2026', lang:'Markdown', cat:'awesome',
    desc:'2026 中文电报群/频道/机器人导航大全，聚合 AI、跨境出海、实用工具类中文群。',
    tags:['Awesome', '中文', '导航', '2026'], lic:'MIT', licKind:'permissive', comm:'yes', maint:'active',
    pushedAt:'2026-08-13', stars:4, forks:1, src:'api',
    seen:'2026-09-20', mentions:3, risk:'normal', conf:'medium' },
  { id:'groups', name:'EdmenGU/telegram-groups', url:'https://github.com/EdmenGU/telegram-groups', lang:'Markdown', cat:'awesome',
    desc:'从 5000+ 个电报群/频道/机器人里筛选出的优质推荐。',
    tags:['群组推荐', '筛选'], lic:'Apache-2.0', licKind:'permissive', comm:'yes', maint:'stale',
    pushedAt:'2025-02-05', stars:42, forks:2, src:'api',
    seen:'2026-09-17', mentions:2, risk:'normal', conf:'low' },
  { id:'itgoyo', name:'itgoyo/TelegramBot', url:'https://github.com/itgoyo/TelegramBot', lang:'Markdown', cat:'awesome',
    desc:'中文圈收集较全的"Telegram 机器人大全"。',
    tags:['Awesome', '中文', '大全'], lic:null, licKind:'unknown', comm:'unknown', maint:'active',
    pushedAt:'2026-09-11', stars:1968, forks:106, src:'api',
    seen:'2026-09-17', mentions:1, risk:'normal', conf:'low',
    note:'无 LICENSE 文件：法律上默认「保留所有权利」，商用前需先联系作者授权' },
];

/* 便于其它脚本读取 */
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { PROJECTS, CATEGORIES, LANGS };
}
